package com.sg.ep;

/**
 * The type Test constant.
 */
public class TestConstant {

    /**
     * The constant EMPLOYEE_SEQUENCE.
     */
    public static final String EMPLOYEE_SEQUENCE = "CREATE SEQUENCE hibernate_sequence";
    /**
     * The constant EMPLOYEE_TABLE_CREATE.
     */
    public static final String EMPLOYEE_TABLE_CREATE = "\n" +
            "CREATE TABLE employee\n" +
            "(\n" +
            "    id bigint GENERATED BY DEFAULT AS SEQUENCE hibernate_sequence PRIMARY KEY,\n" +
            "    department character varying(255) NOT NULL,\n" +
            "    dob date,\n" +
            "    first_name character varying(255) NOT NULL,\n" +
            "    gender character(1) NOT NULL,\n" +
            "    last_name character varying(255) NOT NULL\n" +
            ")";
    /**
     * The constant EMPLOYEE_DATA_INSERT.
     */
    public static final String EMPLOYEE_DATA_INSERT = "INSERT INTO employee(\n" +
            "\t department, dob, first_name, gender, last_name)\n" +
            "\tVALUES ( 'EC', '1993-01-01', 'jagan', 'm', 'singh');";
    /**
     * The constant DROP_HSQLDB_SCHEMA.
     */
    public static final String DROP_HSQLDB_SCHEMA = "DROP SCHEMA PUBLIC CASCADE";
}
